# Generated by Django 4.2.7 on 2025-11-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cutoff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branch',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='cutoff.college'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('college', 'name')},
        ),
        migrations.AddConstraint(
            model_name='cutoff',
            constraint=models.UniqueConstraint(fields=('college', 'branch', 'category', 'year', 'round'), name='unique_cutoff'),
        ),
    ]
